# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
    chmod 755 ./opa
    .opa eval -i deployment.yaml -d policies "data.kubernetes.admission.deny" --format=pretty
  displayName: Run opa eval on sample deployment.yaml