# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- bash: |
    curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
    chmod 755 ./opa
    ./opa eval --fail-defined "data.kubernetes.admission.deny[reason]" -i deployment.yaml -d policies -f pretty
  displayName: Run opa eval on sample deployment.yaml